# pre-commit is a tool to perform a predefined set of tasks manually and/or
# automatically before git commits are made.
#
# Config reference: https://pre-commit.com/#pre-commit-configyaml---top-level
#
# Common tasks
#
# - Run on all files:   pre-commit run --all-files
# - Register git hooks: pre-commit install --install-hooks
#
repos:
  # Autoformat: Python code, syntax patterns are modernized
  - repo: https://github.com/asottile/pyupgrade
    rev: 75992aaa40730136014f34227e0135f63fc951b4 # frozen: v3.21.2
    hooks:
      - id: pyupgrade
        args:
          - --py38-plus

  # Autoformat: Python code
  - repo: https://github.com/PyCQA/autoflake
    rev: 988e469555a54b0b16e39faf16ae84ff247fd337 # frozen: v2.3.3
    hooks:
      - id: autoflake
        # args ref: https://github.com/PyCQA/autoflake#advanced-usage
        args:
          - --in-place

  # Autoformat: Python code
  - repo: https://github.com/pycqa/isort
    rev: 7f321d375f31a2f03833bc9a548e8783f2b5c420 # frozen: 9.0.0b1
    hooks:
      - id: isort

  # Autoformat: Python code
  - repo: https://github.com/psf/black
    rev: 87928e6d6761a4a6d22250e1fee5601b3998086e # frozen: 26.5.1
    hooks:
      - id: black

  # Autoformat: markdown, yaml, javascript (see the file .prettierignore)
  - repo: https://github.com/rbubley/mirrors-prettier
    rev: 0ee178619d696787ca73d210cc191d720868c631 # frozen: v3.9.6
    hooks:
      - id: prettier

  # Autoformat and linting, misc. details
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c # frozen: v6.0.0
    hooks:
      - id: end-of-file-fixer
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: requirements-txt-fixer

  # Linting: Python code (see the file .flake8)
  - repo: https://github.com/PyCQA/flake8
    rev: "c48217e1fc006c2dddd14df54e83b67da15de5cd" # frozen: 7.3.0
    hooks:
      - id: flake8

# pre-commit.ci config reference: https://pre-commit.ci/#configuration
ci:
  autoupdate_schedule: monthly
